// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"time"
)

type Session struct {
	ID        string
	UserID    int64
	CreatedAt time.Time
	Ttl       int64
}

type User struct {
	ID        int64
	UserName  string
	Password  []byte
	CreatedAt time.Time
}
